packloadall

syntax on
set termguicolors     " enable true colors support
set noswapfile
set number
set relativenumber
set scrolloff=8
set expandtab
set tabstop=2 softtabstop=2
set shiftwidth=2
set shiftround
set hlsearch
set incsearch
set showcmd
"set guicursor

hi QuickFixLine term=reverse ctermbg=52 guibg=Cyan
colorscheme peachpuff

call plug#begin('~/.vim/plugged')
" post install (yarn install | npm install) then load plugin only for editing supported files
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install --frozen-lockfile --production',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'svelte', 'yaml', 'html'] }
Plug 'tpope/vim-fugitive',
Plug 'tpope/vim-surround',
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'dense-analysis/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0


let g:ale_completion_enabled = 1
let g:ale_completion_autoimport = 1
let g:ale_fix_on_save = 1

"let ayucolor="dark"   " for dark version of theme
let g:airline_theme = 'papercolor'

let mapleader = " "
nnoremap <leader>pv :Vex<CR> " project view
nnoremap <leader><CR> :so ~/.vim/vimrc<CR>
nnoremap <C-p> :GFiles<CR>
nnoremap <leader>pf :Files<CR>
nnoremap <leader><leader> <C-^> " alternate file
