packloadall

syntax on
set termguicolors     " enable true colors support
set noswapfile
set number relativenumber
set scrolloff=8
set expandtab tabstop=2 softtabstop=2 shiftwidth=2 shiftround
set hlsearch incsearch
set showcmd
set equalalways
set bg=dark

hi QuickFixLine term=reverse ctermbg=52 guibg=Cyan

call plug#begin('~/.vim/plugged')
  Plug 'morhetz/gruvbox',
  Plug 'tpope/vim-fugitive',
  Plug 'tpope/vim-surround',
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'dense-analysis/ale'
call plug#end()

colorscheme gruvbox

let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0

let g:ale_completion_enabled = 1
let g:ale_completion_autoimport = 1
let g:ale_fix_on_save = 1

let mapleader = " "
nnoremap <leader>pv :Vex<CR> " project view
nnoremap <leader><CR> :so ~/.vim/vimrc<CR>
nnoremap <C-p> :GFiles<CR>
nnoremap <leader>pf :Files<CR>
nnoremap <leader><leader> <C-^> " alternate file

xnoremap . :normal .<CR> "visual dot command
